option(PS2X_ENABLE_VU_NATIVE_PAIRS "Build experimental same-source native VU pair kernels" OFF)
set(PS2X_VU_NATIVE_PAIRS_FILE "" CACHE FILEPATH "Private replay-derived VU pair recipe")
set(PS2X_VU_NATIVE_PAIR_LIMIT "64" CACHE STRING "Maximum private VU pair kernels to compile")
option(PS2X_ENABLE_VU_NATIVE_BLOCKS "Build experimental whole-block VU kernels" OFF)
set(PS2X_VU_NATIVE_BLOCK_LIMIT "1" CACHE STRING "Maximum private whole-block VU kernels to compile")
set(PS2X_VU_NATIVE_BLOCK_SELECTION "frequency" CACHE STRING "Native VU block selection: frequency or coverage")
set_property(CACHE PS2X_VU_NATIVE_BLOCK_SELECTION PROPERTY STRINGS frequency coverage)

if(NOT PS2X_ENABLE_VU_NATIVE_PAIRS)
    return()
endif()
if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "The experimental VU pair kernels currently require Windows MSVC x64")
endif()
if(PS2X_ENABLE_VU_DETAIL_PROFILE)
    message(FATAL_ERROR "Native VU pair timing requires detailed per-instruction profiling to be disabled")
endif()
if(NOT PS2X_VU_NATIVE_PAIR_LIMIT MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "PS2X_VU_NATIVE_PAIR_LIMIT must be a positive integer")
endif()
math(EXPR private_pair_limit "${PS2X_VU_NATIVE_PAIR_LIMIT}")
if(private_pair_limit GREATER 512)
    message(FATAL_ERROR "PS2X_VU_NATIVE_PAIR_LIMIT cannot exceed 512")
endif()
if(PS2X_ENABLE_VU_NATIVE_BLOCKS)
    if(NOT PS2X_VU_NATIVE_BLOCK_LIMIT MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "PS2X_VU_NATIVE_BLOCK_LIMIT must be a positive integer")
    endif()
    math(EXPR private_block_limit "${PS2X_VU_NATIVE_BLOCK_LIMIT}")
    if(private_block_limit GREATER 64)
        message(FATAL_ERROR "PS2X_VU_NATIVE_BLOCK_LIMIT cannot exceed 64")
    endif()
endif()

set(native_pair_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/lib/vu")
set(pair_recipe_sources "${native_pair_dir}/ps2_vu1_native_pair_synthetic.inc")
if(PS2X_VU_NATIVE_PAIRS_FILE)
    if(NOT EXISTS "${PS2X_VU_NATIVE_PAIRS_FILE}")
        message(FATAL_ERROR "VU pair recipe does not exist: ${PS2X_VU_NATIVE_PAIRS_FILE}")
    endif()
    list(APPEND pair_recipe_sources "${PS2X_VU_NATIVE_PAIRS_FILE}")
endif()

set(selected_pair_keys "")
set(selected_pair_lowers "")
set(selected_pair_uppers "")
set(private_pairs_selected 0)
set(recipe_block_starts "")
set(recipe_block_start_values "")
set(recipe_block_counts "")
set(recipe_block_private "")
set(recipe_pair_pcs "")
set(recipe_pair_pc_values "")
set(recipe_pair_lowers "")
set(recipe_pair_uppers "")
set(recipe_pair_private "")
set(recipe_hit_pcs "")
foreach(source IN LISTS pair_recipe_sources)
    file(SIZE "${source}" source_size)
    if(source_size GREATER 262144)
        message(FATAL_ERROR "VU pair recipe exceeds 256 KiB: ${source}")
    endif()
    set(source_pair_keys "")
    set(private_source FALSE)
    if(PS2X_VU_NATIVE_PAIRS_FILE AND source STREQUAL PS2X_VU_NATIVE_PAIRS_FILE)
        set(private_source TRUE)
    endif()
    file(STRINGS "${source}" source_lines)
    foreach(line IN LISTS source_lines)
        if(line MATCHES "^[ \t]*//" OR line MATCHES "^[ \t]*$")
            continue()
        elseif(line MATCHES "^VU_NATIVE_ENTRY\\(0x([0-9a-fA-F]+)u\\)$")
            string(LENGTH "${CMAKE_MATCH_1}" digits)
            if(NOT digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair entry line: ${line}")
            endif()
        elseif(line MATCHES "^VU_NATIVE_BLOCK\\(0x([0-9a-fA-F]+)u, ([1-8])u\\)$")
            set(block_pc "${CMAKE_MATCH_1}")
            set(block_count "${CMAKE_MATCH_2}")
            string(LENGTH "${block_pc}" digits)
            if(NOT digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair block line: ${line}")
            endif()
            string(TOLOWER "${block_pc}" block_pc)
            math(EXPR block_pc_value "0x${block_pc}")
            list(APPEND recipe_block_starts "${block_pc}")
            list(APPEND recipe_block_start_values "${block_pc_value}")
            list(APPEND recipe_block_counts "${block_count}")
            list(APPEND recipe_block_private "${private_source}")
        elseif(line MATCHES "^VU_NATIVE_PAIR\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u\\)$")
            set(pc_hex "${CMAKE_MATCH_1}")
            set(lower_hex "${CMAKE_MATCH_2}")
            set(upper_hex "${CMAKE_MATCH_3}")
            string(LENGTH "${pc_hex}" pc_digits)
            string(LENGTH "${lower_hex}" lower_digits)
            string(LENGTH "${upper_hex}" upper_digits)
            if(NOT pc_digits EQUAL 4 OR NOT lower_digits EQUAL 8 OR NOT upper_digits EQUAL 8)
                message(FATAL_ERROR "Invalid VU pair provenance line: ${line}")
            endif()
            string(TOLOWER "${pc_hex}" pc_hex)
            string(TOLOWER "${lower_hex}" lower_hex)
            string(TOLOWER "${upper_hex}" upper_hex)
            math(EXPR pc_value "0x${pc_hex}")
            list(APPEND recipe_pair_pcs "${pc_hex}")
            list(APPEND recipe_pair_pc_values "${pc_value}")
            list(APPEND recipe_pair_lowers "${lower_hex}")
            list(APPEND recipe_pair_uppers "${upper_hex}")
            list(APPEND recipe_pair_private "${private_source}")
        elseif(line MATCHES "^VU_NATIVE_PC_HITS\\(0x([0-9a-fA-F]+)u, ([1-9][0-9]*)u\\)$")
            set(hit_pc "${CMAKE_MATCH_1}")
            set(hit_count "${CMAKE_MATCH_2}")
            string(LENGTH "${hit_pc}" pc_digits)
            string(LENGTH "${hit_count}" count_digits)
            if(NOT private_source OR NOT pc_digits EQUAL 4 OR count_digits GREATER 9)
                message(FATAL_ERROR "Invalid VU PC execution count: ${line}")
            endif()
            math(EXPR hit_pc_value "0x${hit_pc}")
            math(EXPR pc_alignment "${hit_pc_value} % 8")
            if(hit_pc_value GREATER_EQUAL 16384 OR NOT pc_alignment EQUAL 0 OR
               hit_count GREATER 100000000 OR hit_pc_value IN_LIST recipe_hit_pcs)
                message(FATAL_ERROR "Invalid or duplicate VU PC execution count: ${line}")
            endif()
            list(APPEND recipe_hit_pcs "${hit_pc_value}")
            set(vu_hits_${hit_pc_value} "${hit_count}")
        elseif(line MATCHES "^VU_NATIVE_PAIR_WORDS\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u, ([1-9][0-9]*)u\\)$")
            set(lower_hex "${CMAKE_MATCH_1}")
            set(upper_hex "${CMAKE_MATCH_2}")
            set(hit_text "${CMAKE_MATCH_3}")
            string(LENGTH "${lower_hex}" lower_digits)
            string(LENGTH "${upper_hex}" upper_digits)
            string(LENGTH "${hit_text}" hit_digits)
            if(NOT lower_digits EQUAL 8 OR NOT upper_digits EQUAL 8 OR hit_digits GREATER 20)
                message(FATAL_ERROR "Invalid VU pair words line: ${line}")
            endif()
            string(TOLOWER "${lower_hex}${upper_hex}" pair_key)
            list(FIND source_pair_keys "${pair_key}" source_duplicate)
            if(NOT source_duplicate EQUAL -1)
                message(FATAL_ERROR "Duplicate VU pair words in ${source}: ${line}")
            endif()
            list(APPEND source_pair_keys "${pair_key}")
            list(FIND selected_pair_keys "${pair_key}" selected_duplicate)
            if(selected_duplicate EQUAL -1 AND (NOT private_source OR private_pairs_selected LESS private_pair_limit))
                list(APPEND selected_pair_keys "${pair_key}")
                string(TOLOWER "${lower_hex}" lower_hex)
                string(TOLOWER "${upper_hex}" upper_hex)
                list(APPEND selected_pair_lowers "0x${lower_hex}u")
                list(APPEND selected_pair_uppers "0x${upper_hex}u")
                if(private_source)
                    math(EXPR private_pairs_selected "${private_pairs_selected} + 1")
                endif()
            endif()
        elseif(line MATCHES "^VU_NATIVE_EDGE\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u\\)$")
            set(from_hex "${CMAKE_MATCH_1}")
            set(to_hex "${CMAKE_MATCH_2}")
            string(LENGTH "${from_hex}" from_digits)
            string(LENGTH "${to_hex}" to_digits)
            if(NOT from_digits EQUAL 4 OR NOT to_digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair edge line: ${line}")
            endif()
        else()
            message(FATAL_ERROR "Invalid VU pair recipe line in ${source}: ${line}")
        endif()
    endforeach()
endforeach()

foreach(hit_pc IN LISTS recipe_hit_pcs)
    if(NOT hit_pc IN_LIST recipe_pair_pc_values)
        message(FATAL_ERROR "VU execution count has no instruction provenance: ${hit_pc}")
    endif()
endforeach()

list(LENGTH selected_pair_keys pair_count)
if(pair_count EQUAL 0)
    message(FATAL_ERROR "VU pair recipe contains no kernels")
endif()
set(pair_dispatch_declarations "")
set(pair_dispatch_cases "")
set(pair_kernel_sources "")
set(batch_source "")
set(index 0)
math(EXPR pair_last "${pair_count} - 1")
foreach(pair_index RANGE 0 ${pair_last})
    list(GET selected_pair_lowers ${pair_index} lower)
    list(GET selected_pair_uppers ${pair_index} upper)
    math(EXPR slot "${index} % 4")
    if(slot EQUAL 0)
        set(batch_source "#include \"ps2_vu1_native_pair_kernels.inl\"\n")
    endif()
    string(APPEND pair_dispatch_declarations
        "void vuNativePairKernel_${index}(VU1Interpreter *, const void *, uint8_t *, uint32_t, GS &, PS2Memory *);\n")
    string(APPEND pair_dispatch_cases
        "    case (uint64_t{${upper}} << 32u) | ${lower}: return &vuNativePairKernel_${index};\n")
    string(APPEND batch_source
        "void vuNativePairKernel_${index}(VU1Interpreter *vu, const void *decoded, uint8_t *data, uint32_t size, GS &gs, PS2Memory *memory) { VUNativePairAccess::execute<${lower}, ${upper}>(vu, decoded, data, size, gs, memory); }\n")
    math(EXPR index "${index} + 1")
    if(slot EQUAL 3 OR index EQUAL pair_count)
        set(batch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_pair_batch_${index}.cpp")
        file(CONFIGURE OUTPUT "${batch_path}" CONTENT "${batch_source}" @ONLY)
        list(APPEND pair_kernel_sources "${batch_path}")
    endif()
endforeach()

set(dispatch_source "#include \"runtime/ps2_vu1.h\"\n${pair_dispatch_declarations}\nVU1Interpreter::PairKernel VU1Interpreter::lookupNativePair(uint64_t words)\n{\n    switch (words)\n    {\n${pair_dispatch_cases}    default: return nullptr;\n    }\n}\n")
set(dispatch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_pair_dispatch.cpp")
file(CONFIGURE OUTPUT "${dispatch_path}" CONTENT "${dispatch_source}" @ONLY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${pair_recipe_sources})

set(pair_definitions PS2X_ENABLE_VU_NATIVE_PAIRS=1)
set(pair_object_definitions ${pair_definitions})
if(PS2X_ENABLE_VU_NATIVE_BLOCKS)
    include("${CMAKE_CURRENT_LIST_DIR}/VUNativeBlockSelection.cmake")
    list(APPEND pair_object_definitions PS2X_ENABLE_VU_NATIVE_BLOCKS=1)
endif()
if(PS2X_ENABLE_VU_NATIVE_UPPER)
    list(APPEND pair_object_definitions PS2X_ENABLE_VU_NATIVE_UPPER=1)
    foreach(native_target IN LISTS native_targets)
        if(TARGET ${native_target})
            target_compile_definitions(${native_target} PRIVATE PS2X_ENABLE_VU_NATIVE_PAIRS=1)
        endif()
    endforeach()
endif()
target_compile_definitions(ps2_runtime PUBLIC ${pair_definitions})
target_sources(ps2_runtime PRIVATE "${dispatch_path}")
foreach(source IN LISTS pair_kernel_sources)
    get_filename_component(batch_name "${source}" NAME_WE)
    set(batch_target "ps2_${batch_name}")
    add_library(${batch_target} OBJECT "${source}")
    target_sources(ps2_runtime PRIVATE $<TARGET_OBJECTS:${batch_target}>)
    target_include_directories(${batch_target} PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}" "${native_pair_dir}")
    target_compile_definitions(${batch_target} PRIVATE ${pair_object_definitions} PS2X_BUILD_VU_NATIVE_PAIRS=1)
    target_compile_features(${batch_target} PRIVATE cxx_std_20)
    target_compile_options(${batch_target} PRIVATE /MP1)
    set_target_properties(${batch_target} PROPERTIES UNITY_BUILD OFF)
    EnableFastReleaseMode(${batch_target})
endforeach()
message(STATUS "Experimental native VU pair kernels: ${pair_count} (${private_pairs_selected} private)")

if(PS2X_ENABLE_VU_NATIVE_BLOCKS)
    function(vu_native_block_pair_supported lower_hex upper_hex result_var)
        math(EXPR upper_value "0x${upper_hex}")
        math(EXPR lower_value "0x${lower_hex}")
        math(EXPR i_bit "${upper_value} & 0x80000000")
        math(EXPR halt_bits "${upper_value} & 0x58000000")
        set(supported FALSE)
        if(halt_bits EQUAL 0)
            if(NOT i_bit EQUAL 0 OR lower_hex STREQUAL "00000000" OR
               lower_hex STREQUAL "8000033c")
                set(supported TRUE)
            else()
                math(EXPR lower_op "(${lower_value} >> 25) & 0x7f")
                math(EXPR lower_direct "${lower_value} & 0x3f")
                math(EXPR lower_special
                    "(${lower_value} & 3) | ((${lower_value} >> 4) & 0x7c)")
                if(lower_op EQUAL 0x00 OR lower_op EQUAL 0x01 OR lower_op EQUAL 0x04 OR
                   lower_op EQUAL 0x05 OR lower_op EQUAL 0x08 OR
                   lower_op EQUAL 0x09 OR lower_op EQUAL 0x20 OR
                   lower_op EQUAL 0x21 OR lower_op EQUAL 0x24 OR
                   lower_op EQUAL 0x25 OR lower_op EQUAL 0x28 OR
                   lower_op EQUAL 0x29 OR lower_op EQUAL 0x2c OR
                   lower_op EQUAL 0x2d OR lower_op EQUAL 0x2e OR
                   lower_op EQUAL 0x2f)
                    set(supported TRUE)
                elseif(lower_op EQUAL 0x40)
                    if(lower_direct EQUAL 0x30 OR lower_direct EQUAL 0x31 OR
                       lower_direct EQUAL 0x32 OR lower_direct EQUAL 0x34 OR
                       lower_direct EQUAL 0x35)
                        set(supported TRUE)
                    elseif((lower_direct EQUAL 0x3c OR lower_direct EQUAL 0x3d OR
                            lower_direct EQUAL 0x3e OR lower_direct EQUAL 0x3f) AND
                           (lower_special EQUAL 0x30 OR lower_special EQUAL 0x31 OR
                            lower_special EQUAL 0x34 OR lower_special EQUAL 0x35 OR
                            lower_special EQUAL 0x36 OR lower_special EQUAL 0x37 OR
                            lower_special EQUAL 0x3c OR lower_special EQUAL 0x3d OR
                            lower_special EQUAL 0x3f OR lower_special EQUAL 0x40 OR
                            lower_special EQUAL 0x41 OR lower_special EQUAL 0x42 OR
                            lower_special EQUAL 0x43 OR lower_special EQUAL 0x68 OR
                            lower_special EQUAL 0x69))
                        set(supported TRUE)
                    endif()
                endif()
            endif()
        endif()
        set(${result_var} ${supported} PARENT_SCOPE)
    endfunction()

    function(vu_native_pair_is_branch lower_hex upper_hex result_var)
        math(EXPR upper_value "0x${upper_hex}")
        math(EXPR lower_value "0x${lower_hex}")
        math(EXPR i_bit "${upper_value} & 0x80000000")
        set(is_branch FALSE)
        if(i_bit EQUAL 0)
            math(EXPR lower_op "(${lower_value} >> 25) & 0x7f")
            if(lower_op EQUAL 0x20 OR lower_op EQUAL 0x21 OR
               lower_op EQUAL 0x24 OR lower_op EQUAL 0x25 OR
               lower_op EQUAL 0x28 OR lower_op EQUAL 0x29 OR
               lower_op EQUAL 0x2c OR lower_op EQUAL 0x2d OR
               lower_op EQUAL 0x2e OR lower_op EQUAL 0x2f)
                set(is_branch TRUE)
            endif()
        endif()
        set(${result_var} ${is_branch} PARENT_SCOPE)
    endfunction()

    set(block_dispatch_declarations "")
    set(block_dispatch_cases "")
    set(block_kernel_sources "")
    set(selected_block_starts "")
    set(blocks_selected 0)
    set(private_blocks_selected 0)
    set(block_candidates "")

    # Private provenance records are ranked by replay frequency. Public recipes
    # provide deterministic regression coverage and do not consume that limit.
    foreach(candidate_pc IN LISTS recipe_pair_pcs)
        list(FIND recipe_block_starts "${candidate_pc}" block_recipe_index)
        if(block_recipe_index EQUAL -1)
            continue()
        endif()
        list(GET recipe_block_private ${block_recipe_index} block_is_private)
        list(FIND block_candidates "${candidate_pc}" duplicate_block)
        if(NOT duplicate_block EQUAL -1)
            continue()
        endif()
        list(GET recipe_block_counts ${block_recipe_index} original_block_pair_count)

        math(EXPR block_start_value "0x${candidate_pc}")
        set(block_pair_type_list "")
        set(block_complete TRUE)
        set(block_ends_branch FALSE)
        math(EXPR original_block_pair_last "${original_block_pair_count} - 1")
        foreach(block_pair_index RANGE 0 ${original_block_pair_last})
            math(EXPR pair_pc_value "${block_start_value} + ${block_pair_index} * 8")
            list(FIND recipe_pair_pc_values "${pair_pc_value}" pair_provenance_index)
            if(pair_provenance_index EQUAL -1)
                set(block_complete FALSE)
                break()
            endif()
            list(GET recipe_pair_private ${pair_provenance_index} pair_is_private)
            if(NOT "${pair_is_private}" STREQUAL "${block_is_private}")
                set(block_complete FALSE)
                break()
            endif()
            list(GET recipe_pair_lowers ${pair_provenance_index} block_lower)
            list(GET recipe_pair_uppers ${pair_provenance_index} block_upper)
            vu_native_block_pair_supported(
                "${block_lower}" "${block_upper}" block_pair_supported)
            if(NOT block_pair_supported)
                set(block_complete FALSE)
                break()
            endif()
            list(APPEND block_pair_type_list
                "VUNativePairWords<0x${block_lower}u, 0x${block_upper}u>")
            vu_native_pair_is_branch("${block_lower}" "${block_upper}" pair_is_branch)
            if(pair_is_branch)
                math(EXPR expected_branch_index "${original_block_pair_count} - 2")
                if(NOT block_pair_index EQUAL expected_branch_index)
                    set(block_complete FALSE)
                    break()
                endif()
                set(block_ends_branch TRUE)
            endif()
        endforeach()
        if(NOT block_complete)
            continue()
        endif()

        set(block_pair_count ${original_block_pair_count})
        while(block_pair_count LESS 32 AND NOT block_ends_branch)
            math(EXPR next_block_pc_value
                "${block_start_value} + ${block_pair_count} * 8")
            list(FIND recipe_block_start_values
                "${next_block_pc_value}" next_block_recipe_index)
            if(next_block_recipe_index EQUAL -1)
                break()
            endif()
            list(GET recipe_block_private ${next_block_recipe_index} next_block_is_private)
            if(NOT "${next_block_is_private}" STREQUAL "${block_is_private}")
                break()
            endif()
            list(GET recipe_block_counts ${next_block_recipe_index} next_block_pair_count)
            math(EXPR extended_block_pair_count
                "${block_pair_count} + ${next_block_pair_count}")
            if(extended_block_pair_count GREATER 32)
                break()
            endif()

            set(extension_pair_types "")
            set(extension_complete TRUE)
            set(extension_ends_branch FALSE)
            math(EXPR next_block_pair_last "${next_block_pair_count} - 1")
            foreach(next_pair_index RANGE 0 ${next_block_pair_last})
                math(EXPR pair_pc_value
                    "${next_block_pc_value} + ${next_pair_index} * 8")
                list(FIND recipe_pair_pc_values "${pair_pc_value}" pair_provenance_index)
                if(pair_provenance_index EQUAL -1)
                    set(extension_complete FALSE)
                    break()
                endif()
                list(GET recipe_pair_private ${pair_provenance_index} pair_is_private)
                if(NOT "${pair_is_private}" STREQUAL "${block_is_private}")
                    set(extension_complete FALSE)
                    break()
                endif()
                list(GET recipe_pair_lowers ${pair_provenance_index} block_lower)
                list(GET recipe_pair_uppers ${pair_provenance_index} block_upper)
                vu_native_block_pair_supported(
                    "${block_lower}" "${block_upper}" extension_pair_supported)
                if(NOT extension_pair_supported)
                    set(extension_complete FALSE)
                    break()
                endif()
                list(APPEND extension_pair_types
                    "VUNativePairWords<0x${block_lower}u, 0x${block_upper}u>")
                vu_native_pair_is_branch("${block_lower}" "${block_upper}" pair_is_branch)
                if(pair_is_branch)
                    math(EXPR expected_branch_index "${next_block_pair_count} - 2")
                    if(NOT next_pair_index EQUAL expected_branch_index)
                        set(extension_complete FALSE)
                        break()
                    endif()
                    set(extension_ends_branch TRUE)
                endif()
            endforeach()
            if(NOT extension_complete)
                break()
            endif()
            list(APPEND block_pair_type_list ${extension_pair_types})
            set(block_pair_count ${extended_block_pair_count})
            set(block_ends_branch ${extension_ends_branch})
        endwhile()
        list(JOIN block_pair_type_list ", " block_pair_types)

        list(APPEND block_candidates "${candidate_pc}")
        set(vu_candidate_${candidate_pc}_private "${block_is_private}")
        set(vu_candidate_${candidate_pc}_types "${block_pair_types}")
        set(vu_candidate_${candidate_pc}_original_count "${original_block_pair_count}")
        set(vu_candidate_${candidate_pc}_pcs "")
        math(EXPR last_pair "${block_pair_count} - 1")
        foreach(index RANGE 0 ${last_pair})
            math(EXPR pc "${block_start_value} + ${index} * 8")
            list(APPEND vu_candidate_${candidate_pc}_pcs "${pc}")
        endforeach()
    endforeach()

    vu_select_native_blocks(selected_block_starts "${private_block_limit}"
        "${PS2X_VU_NATIVE_BLOCK_SELECTION}" "${block_candidates}")
    foreach(candidate_pc IN LISTS selected_block_starts)
        set(block_is_private "${vu_candidate_${candidate_pc}_private}")
        set(block_pair_types "${vu_candidate_${candidate_pc}_types}")
        set(original_block_pair_count "${vu_candidate_${candidate_pc}_original_count}")

        set(block_index ${blocks_selected})
        string(CONCAT block_source
            "#include \"ps2_vu1_native_pair_kernels.inl\"\n"
            "uint32_t vuNativeDirectBlock_${block_index}(VU1Interpreter *vu, const uint8_t *code, uint32_t codeSize, uint8_t *data, uint32_t dataSize, GS &gs, PS2Memory *memory, uint64_t budgetEnd) { return VUNativeBlockAccess::executeExtended<0x${candidate_pc}u, ${original_block_pair_count}u, ${block_pair_types}>(vu, code, codeSize, data, dataSize, gs, memory, budgetEnd); }\n")
        set(block_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_direct_block_${block_index}.cpp")
        file(CONFIGURE OUTPUT "${block_path}" CONTENT "${block_source}" @ONLY)
        list(APPEND block_kernel_sources "${block_path}")
        string(APPEND block_dispatch_declarations
            "uint32_t vuNativeDirectBlock_${block_index}(VU1Interpreter *, const uint8_t *, uint32_t, uint8_t *, uint32_t, GS &, PS2Memory *, uint64_t);\n")
        string(APPEND block_dispatch_cases
            "    case 0x${candidate_pc}u: return &vuNativeDirectBlock_${block_index};\n")
        math(EXPR blocks_selected "${blocks_selected} + 1")
        if(block_is_private)
            math(EXPR private_blocks_selected "${private_blocks_selected} + 1")
        endif()
    endforeach()

    if(blocks_selected EQUAL 0)
        message(FATAL_ERROR "No complete supported VU block is available")
    endif()
    string(CONCAT block_dispatch_source
        "#include \"runtime/ps2_vu1.h\"\n${block_dispatch_declarations}"
        "VU1Interpreter::BlockKernel VU1Interpreter::lookupNativeBlock(uint32_t pc)\n"
        "{\n    switch (pc)\n    {\n${block_dispatch_cases}    default: return nullptr;\n    }\n}\n")
    set(block_dispatch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_direct_block_dispatch.cpp")
    file(CONFIGURE OUTPUT "${block_dispatch_path}" CONTENT "${block_dispatch_source}" @ONLY)

    target_compile_definitions(ps2_runtime PUBLIC PS2X_ENABLE_VU_NATIVE_BLOCKS=1)
    target_sources(ps2_runtime PRIVATE "${block_dispatch_path}")
    foreach(source IN LISTS block_kernel_sources)
        get_filename_component(block_name "${source}" NAME_WE)
        set(block_target "ps2_${block_name}")
        add_library(${block_target} OBJECT "${source}")
        target_sources(ps2_runtime PRIVATE $<TARGET_OBJECTS:${block_target}>)
        target_include_directories(${block_target} PRIVATE
            "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}" "${native_pair_dir}")
        target_compile_definitions(${block_target} PRIVATE
            PS2X_ENABLE_VU_NATIVE_PAIRS=1 PS2X_ENABLE_VU_NATIVE_BLOCKS=1
            PS2X_BUILD_VU_NATIVE_PAIRS=1)
        target_compile_features(${block_target} PRIVATE cxx_std_20)
        target_compile_options(${block_target} PRIVATE /MP1)
        set_target_properties(${block_target} PROPERTIES UNITY_BUILD OFF)
        EnableFastReleaseMode(${block_target})
    endforeach()
    message(STATUS "Experimental whole-block VU kernels: ${blocks_selected} (${private_blocks_selected} private)")
endif()
