option(PS2X_ENABLE_VU_NATIVE_PAIRS "Build experimental same-source native VU pair kernels" OFF)
set(PS2X_VU_NATIVE_PAIRS_FILE "" CACHE FILEPATH "Private replay-derived VU pair recipe")
set(PS2X_VU_NATIVE_PAIR_LIMIT "64" CACHE STRING "Maximum private VU pair kernels to compile")

if(NOT PS2X_ENABLE_VU_NATIVE_PAIRS)
    return()
endif()
if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "The experimental VU pair kernels currently require Windows MSVC x64")
endif()
if(PS2X_ENABLE_VU_DETAIL_PROFILE)
    message(FATAL_ERROR "Native VU pair timing requires detailed per-instruction profiling to be disabled")
endif()
if(NOT PS2X_VU_NATIVE_PAIR_LIMIT MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "PS2X_VU_NATIVE_PAIR_LIMIT must be a positive integer")
endif()
math(EXPR private_pair_limit "${PS2X_VU_NATIVE_PAIR_LIMIT}")
if(private_pair_limit GREATER 512)
    message(FATAL_ERROR "PS2X_VU_NATIVE_PAIR_LIMIT cannot exceed 512")
endif()

set(native_pair_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/lib/vu")
set(pair_recipe_sources "${native_pair_dir}/ps2_vu1_native_pair_synthetic.inc")
if(PS2X_VU_NATIVE_PAIRS_FILE)
    if(NOT EXISTS "${PS2X_VU_NATIVE_PAIRS_FILE}")
        message(FATAL_ERROR "VU pair recipe does not exist: ${PS2X_VU_NATIVE_PAIRS_FILE}")
    endif()
    list(APPEND pair_recipe_sources "${PS2X_VU_NATIVE_PAIRS_FILE}")
endif()

set(selected_pair_keys "")
set(selected_pair_lowers "")
set(selected_pair_uppers "")
set(private_pairs_selected 0)
foreach(source IN LISTS pair_recipe_sources)
    file(SIZE "${source}" source_size)
    if(source_size GREATER 262144)
        message(FATAL_ERROR "VU pair recipe exceeds 256 KiB: ${source}")
    endif()
    set(source_pair_keys "")
    set(private_source FALSE)
    if(PS2X_VU_NATIVE_PAIRS_FILE AND source STREQUAL PS2X_VU_NATIVE_PAIRS_FILE)
        set(private_source TRUE)
    endif()
    file(STRINGS "${source}" source_lines)
    foreach(line IN LISTS source_lines)
        if(line MATCHES "^[ \t]*//" OR line MATCHES "^[ \t]*$")
            continue()
        elseif(line MATCHES "^VU_NATIVE_ENTRY\\(0x([0-9a-fA-F]+)u\\)$")
            string(LENGTH "${CMAKE_MATCH_1}" digits)
            if(NOT digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair entry line: ${line}")
            endif()
        elseif(line MATCHES "^VU_NATIVE_BLOCK\\(0x([0-9a-fA-F]+)u, ([1-8])u\\)$")
            string(LENGTH "${CMAKE_MATCH_1}" digits)
            if(NOT digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair block line: ${line}")
            endif()
        elseif(line MATCHES "^VU_NATIVE_PAIR\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u\\)$")
            set(pc_hex "${CMAKE_MATCH_1}")
            set(lower_hex "${CMAKE_MATCH_2}")
            set(upper_hex "${CMAKE_MATCH_3}")
            string(LENGTH "${pc_hex}" pc_digits)
            string(LENGTH "${lower_hex}" lower_digits)
            string(LENGTH "${upper_hex}" upper_digits)
            if(NOT pc_digits EQUAL 4 OR NOT lower_digits EQUAL 8 OR NOT upper_digits EQUAL 8)
                message(FATAL_ERROR "Invalid VU pair provenance line: ${line}")
            endif()
        elseif(line MATCHES "^VU_NATIVE_PAIR_WORDS\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u, ([1-9][0-9]*)u\\)$")
            set(lower_hex "${CMAKE_MATCH_1}")
            set(upper_hex "${CMAKE_MATCH_2}")
            set(hit_text "${CMAKE_MATCH_3}")
            string(LENGTH "${lower_hex}" lower_digits)
            string(LENGTH "${upper_hex}" upper_digits)
            string(LENGTH "${hit_text}" hit_digits)
            if(NOT lower_digits EQUAL 8 OR NOT upper_digits EQUAL 8 OR hit_digits GREATER 20)
                message(FATAL_ERROR "Invalid VU pair words line: ${line}")
            endif()
            string(TOLOWER "${lower_hex}${upper_hex}" pair_key)
            list(FIND source_pair_keys "${pair_key}" source_duplicate)
            if(NOT source_duplicate EQUAL -1)
                message(FATAL_ERROR "Duplicate VU pair words in ${source}: ${line}")
            endif()
            list(APPEND source_pair_keys "${pair_key}")
            list(FIND selected_pair_keys "${pair_key}" selected_duplicate)
            if(selected_duplicate EQUAL -1 AND (NOT private_source OR private_pairs_selected LESS private_pair_limit))
                list(APPEND selected_pair_keys "${pair_key}")
                string(TOLOWER "${lower_hex}" lower_hex)
                string(TOLOWER "${upper_hex}" upper_hex)
                list(APPEND selected_pair_lowers "0x${lower_hex}u")
                list(APPEND selected_pair_uppers "0x${upper_hex}u")
                if(private_source)
                    math(EXPR private_pairs_selected "${private_pairs_selected} + 1")
                endif()
            endif()
        elseif(line MATCHES "^VU_NATIVE_EDGE\\(0x([0-9a-fA-F]+)u, 0x([0-9a-fA-F]+)u\\)$")
            set(from_hex "${CMAKE_MATCH_1}")
            set(to_hex "${CMAKE_MATCH_2}")
            string(LENGTH "${from_hex}" from_digits)
            string(LENGTH "${to_hex}" to_digits)
            if(NOT from_digits EQUAL 4 OR NOT to_digits EQUAL 4)
                message(FATAL_ERROR "Invalid VU pair edge line: ${line}")
            endif()
        else()
            message(FATAL_ERROR "Invalid VU pair recipe line in ${source}: ${line}")
        endif()
    endforeach()
endforeach()

list(LENGTH selected_pair_keys pair_count)
if(pair_count EQUAL 0)
    message(FATAL_ERROR "VU pair recipe contains no kernels")
endif()
set(pair_dispatch_declarations "")
set(pair_dispatch_cases "")
set(pair_kernel_sources "")
set(batch_source "")
set(index 0)
math(EXPR pair_last "${pair_count} - 1")
foreach(pair_index RANGE 0 ${pair_last})
    list(GET selected_pair_lowers ${pair_index} lower)
    list(GET selected_pair_uppers ${pair_index} upper)
    math(EXPR slot "${index} % 4")
    if(slot EQUAL 0)
        set(batch_source "#include \"ps2_vu1_native_pair_kernels.inl\"\n")
    endif()
    string(APPEND pair_dispatch_declarations
        "void vuNativePairKernel_${index}(VU1Interpreter *, const void *, uint8_t *, uint32_t, GS &, PS2Memory *);\n")
    string(APPEND pair_dispatch_cases
        "    case (uint64_t{${upper}} << 32u) | ${lower}: return &vuNativePairKernel_${index};\n")
    string(APPEND batch_source
        "void vuNativePairKernel_${index}(VU1Interpreter *vu, const void *decoded, uint8_t *data, uint32_t size, GS &gs, PS2Memory *memory) { VUNativePairAccess::execute<${lower}, ${upper}>(vu, decoded, data, size, gs, memory); }\n")
    math(EXPR index "${index} + 1")
    if(slot EQUAL 3 OR index EQUAL pair_count)
        set(batch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_pair_batch_${index}.cpp")
        file(CONFIGURE OUTPUT "${batch_path}" CONTENT "${batch_source}" @ONLY)
        list(APPEND pair_kernel_sources "${batch_path}")
    endif()
endforeach()

set(dispatch_source "#include \"runtime/ps2_vu1.h\"\n${pair_dispatch_declarations}\nVU1Interpreter::PairKernel VU1Interpreter::lookupNativePair(uint64_t words)\n{\n    switch (words)\n    {\n${pair_dispatch_cases}    default: return nullptr;\n    }\n}\n")
set(dispatch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_pair_dispatch.cpp")
file(CONFIGURE OUTPUT "${dispatch_path}" CONTENT "${dispatch_source}" @ONLY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${pair_recipe_sources})

set(pair_definitions PS2X_ENABLE_VU_NATIVE_PAIRS=1)
set(pair_object_definitions ${pair_definitions})
if(PS2X_ENABLE_VU_NATIVE_UPPER)
    list(APPEND pair_object_definitions PS2X_ENABLE_VU_NATIVE_UPPER=1)
    foreach(native_target IN LISTS native_targets)
        if(TARGET ${native_target})
            target_compile_definitions(${native_target} PRIVATE PS2X_ENABLE_VU_NATIVE_PAIRS=1)
        endif()
    endforeach()
endif()
target_compile_definitions(ps2_runtime PUBLIC ${pair_definitions})
target_sources(ps2_runtime PRIVATE "${dispatch_path}")
foreach(source IN LISTS pair_kernel_sources)
    get_filename_component(batch_name "${source}" NAME_WE)
    set(batch_target "ps2_${batch_name}")
    add_library(${batch_target} OBJECT "${source}")
    target_sources(ps2_runtime PRIVATE $<TARGET_OBJECTS:${batch_target}>)
    target_include_directories(${batch_target} PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}" "${native_pair_dir}")
    target_compile_definitions(${batch_target} PRIVATE ${pair_object_definitions} PS2X_BUILD_VU_NATIVE_PAIRS=1)
    target_compile_features(${batch_target} PRIVATE cxx_std_20)
    target_compile_options(${batch_target} PRIVATE /MP1)
    set_target_properties(${batch_target} PROPERTIES UNITY_BUILD OFF)
    EnableFastReleaseMode(${batch_target})
endforeach()
message(STATUS "Experimental native VU pair kernels: ${pair_count} (${private_pairs_selected} private)")
