option(PS2X_ENABLE_VU_NATIVE_UPPER "Build experimental same-source native VU upper kernels" OFF)
set(PS2X_VU_NATIVE_WORDS_FILE "" CACHE FILEPATH "Private replay-derived upper instruction recipe")

if(NOT PS2X_ENABLE_VU_NATIVE_UPPER)
    return()
endif()
if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "The experimental VU upper module currently requires Windows MSVC x64")
endif()
if(PS2X_ENABLE_VU_DETAIL_PROFILE)
    message(FATAL_ERROR "Native VU timing comparisons require detailed per-instruction profiling to be disabled")
endif()

set(native_dir "${CMAKE_CURRENT_SOURCE_DIR}/src/lib/vu")
set(words_sources "${native_dir}/ps2_vu1_native_synthetic.inc")
if(PS2X_VU_NATIVE_WORDS_FILE)
    list(APPEND words_sources "${PS2X_VU_NATIVE_WORDS_FILE}")
endif()
set(words "")
foreach(source IN LISTS words_sources)
    file(SIZE "${source}" source_size)
    if(source_size GREATER 65536)
        message(FATAL_ERROR "VU upper recipe exceeds 64 KiB: ${source}")
    endif()
    file(STRINGS "${source}" source_lines)
    foreach(line IN LISTS source_lines)
        if(line MATCHES "^[ \t]*//" OR line MATCHES "^[ \t]*$")
            continue()
        endif()
        if(NOT line MATCHES "^VU_NATIVE_WORD\\(0x([0-9a-fA-F]+)u\\)$")
            message(FATAL_ERROR "Invalid line in VU upper recipe: ${source}")
        endif()
        string(LENGTH "${CMAKE_MATCH_1}" digits)
        if(NOT digits EQUAL 8)
            message(FATAL_ERROR "VU upper words must have exactly eight hexadecimal digits")
        endif()
        string(TOLOWER "${line}" word)
        string(REPLACE "vu_native_word" "VU_NATIVE_WORD" word "${word}")
        list(APPEND words "${word}")
    endforeach()
endforeach()
list(REMOVE_DUPLICATES words)
list(LENGTH words word_count)
if(word_count GREATER 512)
    message(FATAL_ERROR "VU upper prototype is limited to 512 kernels")
endif()
set(kernel_sources "")
set(dispatch "")
set(index 0)
set(batch_source "")
foreach(word IN LISTS words)
    math(EXPR slot "${index} % 8")
    if(slot EQUAL 0)
        set(batch_source "#include \"ps2_vu1_native_kernels.inl\"\n")
    endif()
    string(REGEX REPLACE "^VU_NATIVE_WORD\\((.+)\\)$" "\\1" literal "${word}")
    string(APPEND dispatch "VU_NATIVE_KERNEL(${index}, ${literal})\n")
    string(APPEND batch_source "void vuNativeKernel_${index}(VU1Interpreter *vu) { VUNativeAccess::execute<${literal}>(vu); }\n")
    math(EXPR index "${index} + 1")
    if(slot EQUAL 7 OR index EQUAL word_count)
        set(batch_path "${CMAKE_CURRENT_BINARY_DIR}/vu_native_batch_${index}.cpp")
        file(CONFIGURE OUTPUT "${batch_path}" CONTENT "${batch_source}" @ONLY)
        list(APPEND kernel_sources "${batch_path}")
    endif()
endforeach()
file(CONFIGURE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/vu_native_dispatch.inc" CONTENT "${dispatch}" @ONLY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${words_sources})

set(abi_sources
    "${CMAKE_CURRENT_SOURCE_DIR}/include/runtime/ps2_vu1.h"
    "${CMAKE_CURRENT_SOURCE_DIR}/include/runtime/ps2_vu1_native.h"
    "${native_dir}/ps2_vu1_math.inl"
    "${native_dir}/ps2_vu1_upper.cpp"
    "${native_dir}/ps2_vu1_detail.h")
set(abi_hashes "")
foreach(source IN LISTS abi_sources)
    file(SHA256 "${source}" source_hash)
    string(APPEND abi_hashes "${source_hash}")
endforeach()
string(SHA256 abi_hash "${abi_hashes}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${abi_sources})
set(native_build_dir "${CMAKE_CURRENT_BINARY_DIR}/vu-native/$<CONFIG>")
# Only ABI consumers need rebuilding when arithmetic changes, not every guest source.
file(GENERATE OUTPUT "${native_build_dir}/vu_native_build_id.h" CONTENT
    "#pragma once\n#define PS2X_VU_NATIVE_FINGERPRINT \"${abi_hash}\"\n#define PS2X_VU_NATIVE_CONFIGURATION \"$<CONFIG>\"\n")
set(native_definitions PS2X_ENABLE_VU_NATIVE_UPPER=1)
target_compile_definitions(ps2_runtime PUBLIC ${native_definitions})
target_include_directories(ps2_runtime PUBLIC "${native_build_dir}")
target_sources(ps2_runtime PRIVATE
    "${native_dir}/ps2_vu1_native_host.cpp"
    "${native_dir}/ps2_vu1_native_loader.cpp")

add_library(ps2_vu_native_upper MODULE "${native_dir}/ps2_vu1_native_module.cpp")
set(native_targets ps2_vu_native_upper)
foreach(source IN LISTS kernel_sources)
    get_filename_component(batch_name "${source}" NAME_WE)
    set(batch_target "ps2_${batch_name}")
    # Separate targets prevent MSVC from batching many files into one compiler process.
    add_library(${batch_target} OBJECT "${source}")
    target_sources(ps2_vu_native_upper PRIVATE $<TARGET_OBJECTS:${batch_target}>)
    list(APPEND native_targets ${batch_target})
endforeach()
foreach(native_target IN LISTS native_targets)
    target_include_directories(${native_target} PRIVATE
        "${CMAKE_CURRENT_SOURCE_DIR}/include" "${CMAKE_CURRENT_BINARY_DIR}" "${native_dir}"
        "${native_build_dir}")
    set_target_properties(${native_target} PROPERTIES UNITY_BUILD OFF)
    target_compile_definitions(${native_target} PRIVATE ${native_definitions} PS2X_BUILD_VU_NATIVE_UPPER=1)
    target_compile_features(${native_target} PRIVATE cxx_std_20)
    target_compile_options(${native_target} PRIVATE /MP1)
    EnableFastReleaseMode(${native_target})
endforeach()
add_dependencies(ps2EntryRunner ps2_vu_native_upper)
message(STATUS "Experimental native VU upper kernels: ${word_count}")
