# Candidates carry private/public ownership and exact instruction-PC lists.
# Weights are retired execution counts, never ordinal positions in the recipe.
function(vu_select_native_blocks result_var limit strategy candidates)
    if(NOT strategy STREQUAL "frequency" AND NOT strategy STREQUAL "coverage")
        message(FATAL_ERROR "Unknown native VU block selection: ${strategy}")
    endif()
    if(NOT limit MATCHES "^[1-9][0-9]*$" OR limit GREATER 64)
        message(FATAL_ERROR "Native VU block selection limit must be 1..64")
    endif()
    set(selected "")
    set(remaining "")
    foreach(candidate IN LISTS candidates)
        if(vu_candidate_${candidate}_private)
            list(APPEND remaining "${candidate}")
            if(strategy STREQUAL "coverage")
                foreach(pc IN LISTS vu_candidate_${candidate}_pcs)
                    if(NOT DEFINED vu_hits_${pc} OR
                       NOT "${vu_hits_${pc}}" MATCHES "^[1-9][0-9]*$" OR
                       vu_hits_${pc} GREATER 100000000)
                        message(FATAL_ERROR "Missing or invalid retired execution count for VU PC ${pc}")
                    endif()
                    set(covered_${pc} 0)
                endforeach()
            endif()
        else()
            list(APPEND selected "${candidate}")
        endif()
    endforeach()
    set(private_count 0)
    while(NOT "${remaining}" STREQUAL "" AND private_count LESS limit)
        if(strategy STREQUAL "frequency")
            list(GET remaining 0 best)
        else()
            set(best "")
            set(best_score 0)
            foreach(candidate IN LISTS remaining)
                set(score 0)
                list(GET vu_candidate_${candidate}_pcs 0 entry_pc)
                foreach(pc IN LISTS vu_candidate_${candidate}_pcs)
                    set(contribution "${vu_hits_${entry_pc}}")
                    if(vu_hits_${pc} LESS contribution)
                        set(contribution "${vu_hits_${pc}}")
                    endif()
                    if(contribution GREATER covered_${pc})
                        math(EXPR score "${score} + ${contribution} - ${covered_${pc}}")
                    endif()
                endforeach()
                # Equal scores retain the deterministic recipe order.
                if(score GREATER best_score)
                    set(best "${candidate}")
                    set(best_score "${score}")
                endif()
            endforeach()
            if(best STREQUAL "")
                break()
            endif()
            list(GET vu_candidate_${best}_pcs 0 entry_pc)
            foreach(pc IN LISTS vu_candidate_${best}_pcs)
                set(contribution "${vu_hits_${entry_pc}}")
                if(vu_hits_${pc} LESS contribution)
                    set(contribution "${vu_hits_${pc}}")
                endif()
                if(contribution GREATER covered_${pc})
                    set(covered_${pc} "${contribution}")
                endif()
            endforeach()
        endif()
        list(APPEND selected "${best}")
        list(REMOVE_ITEM remaining "${best}")
        math(EXPR private_count "${private_count} + 1")
    endwhile()
    set(${result_var} "${selected}" PARENT_SCOPE)
endfunction()
