include("${CMAKE_CURRENT_LIST_DIR}/../VUNativeBlockSelection.cmake")
set(candidates public a b c d)
set(vu_candidate_public_private FALSE)
foreach(candidate a b c d)
    set(vu_candidate_${candidate}_private TRUE)
endforeach()
set(vu_candidate_a_pcs 0 8 16)
set(vu_candidate_b_pcs 8 16)
set(vu_candidate_c_pcs 24 32)
set(vu_candidate_d_pcs 40 48)
foreach(pc 0 8 16)
    set(vu_hits_${pc} 100)
endforeach()
foreach(pc 24 32 40 48)
    set(vu_hits_${pc} 20)
endforeach()

if(DEFINED CASE)
    if(CASE STREQUAL "missing")
        unset(vu_hits_8)
    elseif(CASE STREQUAL "zero")
        set(vu_hits_8 0)
    elseif(CASE STREQUAL "negative")
        set(vu_hits_8 -1)
    elseif(CASE STREQUAL "overflow")
        set(vu_hits_8 100000001)
    elseif(CASE STREQUAL "text")
        set(vu_hits_8 garbage)
    elseif(CASE STREQUAL "strategy")
        vu_select_native_blocks(actual 2 unknown "${candidates}")
        return()
    elseif(CASE STREQUAL "limit")
        vu_select_native_blocks(actual 65 coverage "${candidates}")
        return()
    endif()
    vu_select_native_blocks(actual 2 coverage "${candidates}")
    return()
endif()

function(expect actual expected)
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected '${expected}', got '${actual}'")
    endif()
endfunction()
vu_select_native_blocks(actual 2 frequency "${candidates}")
expect("${actual}" "public;a;b")
vu_select_native_blocks(actual 2 coverage "${candidates}")
expect("${actual}" "public;a;c")
vu_select_native_blocks(actual 1 coverage "${candidates}")
expect("${actual}" "public;a")
vu_select_native_blocks(actual 10 coverage "${candidates}")
expect("${actual}" "public;a;c;d")
set(vu_candidate_rare_private TRUE)
set(vu_candidate_rare_pcs 56 0 8 16)
set(vu_hits_56 1)
vu_select_native_blocks(actual 2 coverage "rare;${candidates}")
expect("${actual}" "public;a;c")
unset(vu_hits_8)
vu_select_native_blocks(actual 2 frequency "${candidates}")
expect("${actual}" "public;a;b")
set(vu_candidate_0000_private TRUE)
set(vu_candidate_0000_pcs 0)
foreach(strategy frequency coverage)
    vu_select_native_blocks(actual 1 "${strategy}" "0000")
    expect("${actual}" "0000")
endforeach()
foreach(case missing zero negative overflow text strategy limit)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(result EQUAL 0)
        message(FATAL_ERROR "Invalid ${case} input was accepted")
    endif()
endforeach()
message(STATUS "VU block selection: eight selection and seven rejection checks passed")
